trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/*
    - this-is-me/*

pool:
  name: 'Default'

parameters:
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: Release
    values:
      - release
      - debug

variables:
  frontendImageName: 'tvpow3r/frontend-app'

stages:
  - stage: Build
    displayName: Build and Push stage
    jobs:
      - job: BuildAndPushFrontendJob
        displayName: Build Next.js FE
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              containerRegistry: 'DockerHub-Tvpow3r'
              repository: $(frontendImageName)
              dockerfile: 'frontend/Dockerfile'

  - stage: Deployment
    displayName: Deploy Stage
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy with Helm
        steps:
          - script: |
              helm upgrade --install this-is-me ./this-is-me \
              --namespace this-is-me \
              --reuse-values \
              --set frontend.DockerImage=tvpow3r/frontend-app:$(Build.BuildId)
            displayName: Deploy with Helm
            env:
              KUBECONFIG: /Users/tvpower/.kube/config

#              --create-namespace \ had this before
