trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/* # This is what makes so it triggers only when the frontend changes
    - docker-compose.yml # Triggers if the compose config changes

pool:
  name: 'Default'

parameters:
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: Release
    values:
      - release
      - debug

variables:
  frontendImageName: 'frontend-app'

stages:
  - stage: Build
    displayName: Build and Push stage
    jobs:
      - job: BuildAndPushFrontendJob
        displayName: Build Next.js FE
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: build
              repository: $(frontendImageName)
              dockerfile: 'frontend/Dockerfile'

  - stage: Deployment
    displayName: Deploy stage
    dependsOn: Build
    jobs:
    - job: Deploy
      displayName: Deploy FE
      steps:
      - script: |
          # Only targets the frontend service so the backend stays online
          docker compose up -d --build frontend:$(Build.BuildId)
        displayName: 'Restart Frontend Container'
        env:
          FRONTEND_TAG: $(Build.BuildId)


