trigger:
  branches:
     include:
     - main
  paths:
    include:
    - backend/*
    - docker-compose.yml

pool:
  name: 'Default'

parameters:
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: release
    values:
      - release
      - debug

variables:
  backendImageName: 'tvpow3r/backend-app'

stages:
  - stage: Build
    displayName: Build and Push Stage
    jobs:
      - job: BuildBackend
        displayName: Build Backend Image
        steps:
          - task: Docker@2
            displayName: Build Backend
            inputs:
              command: buildAndPush
              containerRegistry: 'DockerHub-Tvpow3r'
              repository: $(backendImageName)
              dockerfile: 'backend/Dockerfile'

  - stage: Deployment
    displayName: Deploy stage
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy Backend
        steps:
          - script: |
              docker compose pull backend
              docker compose up -d backend
            displayName: 'Restart Backend container'
            env:
              DB_NAME: $(DB_NAME)
              DB_USER: $(DB_USER)
              DB_PASSWORD: $(DB_PASSWORD)
              DB_ROOT_PASSWORD: $(DB_ROOT_PASSWORD)
              BACKEND_TAG: $(Build.BuildId)

