trigger:
  branches:
     include:
     - main
  paths:
    include:
    - backend/*
    - this-is-me/*

pool:
  name: 'Default'

parameters:
  - name: buildConfiguration
    displayName: Build Configuration
    type: string

variables:
  backendImageName: 'tvpow3r/backend-app'

stages:
  - stage: Build
    displayName: Build and Push Stage
    jobs:
      - job: BuildBackend
        displayName: Build Backend Image
        steps:
          - task: Docker@2
            displayName: Build Backend
            inputs:
              command: buildAndPush
              containerRegistry: 'DockerHub-Tvpow3r'
              repository: $(backendImageName)
              dockerfile: 'backend/Dockerfile'

  - stage: Deployment
    displayName: Deploy Stage
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy with Helm
        steps:
          - script: |
              helm upgrade --install this-is-me ./this-is-me \
              --namespace this-is-me \
              --create-namespace \
              --reuse-values \
              --set backend.DockerImage=tvpow3r/backend-app:$(Build.BuildId)
            displayName: Deploy with Helm
            env:
              KUBECONFIG: /Users/tvpower/.kube/config

#              --create-namespace \ had this before