trigger:
  branches:
     include:
     - main
  paths:
    include:
    - backend/*
    - docker-compose.yml

pool:
  name: 'Default'

parameters:
  - name: buildConfiguration
    displayName: Build Configuration
    type: string
    default: Release
    values:
      - release
      - debug

variables:
  frontendImageName: 'backend-app'

stages:
  - stage: Build
    displayName: Build and Push Stage
    jobs:
      - job: BuildBackend
        displayName: Build Backend Image
        steps:
          - task: Docker@2
            displayName: Build Backend
            inputs:
              command: build
              repository: $(backendImageName)
              dockerfile: 'backend/Dockerfile'
              tags: 'latest'

  - stage: Deployment
    displayName: Deploy stage
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy Backend
        steps:
          - script: |
              # Only targets the backend service so the frontend stays online
              docker compose up -d --no-deps --build backend
            displayName: Restart Backend container
            env:
              DB_NAME: $(DB_NAME)
              DB_USER: $(DB_USER)
              DB_PASSWORD: $(DB_PASSWORD)
              DB_ROOT_PASSWORD: $(DB_ROOT_PASSWORD)
